# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-02 08:52
from __future__ import unicode_literals

import VTAT_TOOL.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_name', models.CharField(max_length=30, unique=True)),
                ('repository_description', models.CharField(blank=True, max_length=50)),
                ('repository_file', models.FileField(upload_to=VTAT_TOOL.models.get_upload_to)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
