# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 11:49
from __future__ import unicode_literals

import VTAT_TOOL.models
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('VTAT_TOOL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcase_name', models.CharField(max_length=50, unique=True)),
                ('test_iterations', models.CharField(default=1, max_length=50)),
                ('testcase_action', models.CharField(max_length=100)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='VTAT_TOOL.RepositoryData')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VTAT_TOOL.Repository')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_file_name', models.FileField(blank=True, upload_to=VTAT_TOOL.models.get_upload_to_log)),
                ('log_testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VTAT_TOOL.RepositoryData')),
            ],
        ),
    ]
