# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTAT_TOOL', '0003_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlogs',
            name='script_exec_end',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='testlogs',
            name='script_exec_start',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='testlogs',
            name='script_status',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
