# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTAT_TOOL', '0004_auto_20170816_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlogs',
            name='Fail_iterations',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='testlogs',
            name='success_iterations',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
