# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTAT_TOOL', '0005_auto_20170816_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorydata',
            name='log_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='repositorydata',
            name='testcase_action',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
