# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTAT_TOOL', '0006_auto_20170821_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='repository_name',
            field=models.CharField(max_length=30),
        ),
    ]
