# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTAT_TOOL', '0007_auto_20170821_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='repository_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='repositorydata',
            name='testcase_name',
            field=models.CharField(max_length=50),
        ),
    ]
